apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myphp-autoscaling
  namespace: myapp-php
spec:
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myphp-deployment
