apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain.com-tls
  namespace: myapp-php
spec:
  secretName: domain.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "php.domain.com"
