apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain.com-tls
  namespace: myapp-production
spec:
  secretName: domain.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "domain.com"
    - "staging.domain.com"
---