apiVersion: apps/v1
kind: Deployment
metadata:
  name: myphp-deployment
  namespace: myapp-php
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myphp-deployment
  template:
    metadata:
      labels:
        app: myphp-deployment
    spec:
      # imagePullSecrets:
      #   - name: gitlab-token
      containers:
        - name: myphp-deployment
          image: docker.io/randyproxz/php:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi
              cpu: "0.25"
            limits:
              memory: 500Mi
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
      terminationGracePeriodSeconds: 0
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
